export const columnsConfig = {
  genericoDescripcion: [
    {
      name: "id",
      required: true,
      label: "Id",
      align: "left",
      field: (row) => row.id,
      format: (val) => `${val}`,
      sortable: true,
    },
    {
      name: "descripcion",
      align: "left",
      label: "Descripción",
      field: "descripcion",
      sortable: true,
    },
    {
      name: "paridad",
      align: "left",
      label: "Paridad",
      field: "paridad",
      sortable: true,
    },
    {
      name: "activo",
      label: "Activo",
      field: "activo",
      sortable: true,
      align: "center",
    },
    {
      name: "action",
      align: "center",
      field: "action",
      sortable: false,
    },
  ],
  sexo: [
    {
      name: "id",
      required: true,
      label: "Id",
      align: "left",
      field: (row) => row.id,
      format: (val) => `${val}`,
      sortable: true,
    },
    {
      name: "descripcion",
      align: "left",
      label: "Descripción",
      field: "descripcion",
      sortable: true,
    },
    {
      name: "identificador",
      align: "left",
      label: "Identificador",
      field: "identificador",
      sortable: true,
    },
    {
      name: "paridad",
      align: "left",
      label: "Paridad",
      field: "paridad",
      sortable: true,
    },
    {
      name: "activo",
      label: "Activo",
      field: "activo",
      sortable: true,
      align: "center",
    },
    {
      name: "action",
      align: "center",
      field: "action",
      sortable: false,
    },
  ],
  diagnostico: [
    {
      name: "id",
      required: true,
      label: "Id",
      align: "left",
      field: (row) => row.id,
      format: (val) => `${val}`,
      sortable: true,
    },
    {
      name: "descripcion",
      align: "left",
      label: "Descripción",
      field: "descripcion",
      sortable: true,
    },
    {
      name: "paridad",
      align: "left",
      label: "Paridad",
      field: "paridad",
      sortable: true,
    },
    {
      name: "activo",
      label: "Activo",
      field: "activo",
      sortable: true,
      align: "center",
    },
    {
      name: "causamuerte",
      label: "Causa Muerte",
      field: "causamuerte",
      sortable: true,
      align: "center",
    },
    {
      name: "action",
      align: "center",
      field: "action",
      sortable: false,
    },
  ],
  usuario: [
    {
      name: "id",
      required: true,
      label: "Id",
      align: "left",
      field: (row) => row.id,
      format: (val) => `${val}`,
      sortable: true,
    },
    {
      name: "nombreusuario",
      align: "left",
      label: "Nombre usuario",
      field: "nombreusuario",
      sortable: true,
    },
    {
      name: "email",
      label: "Correo electrónico",
      field: "email",
      sortable: true,
      align: "center",
    },
    {
      name: "fechacaducidadclave",
      label: "Vigencia",
      field: "fechacaducidadclave",
      sortable: true,
      align: "center",
    },

    {
      name: "activo",
      label: "Activo",
      field: "activo",
      sortable: true,
      align: "center",
    },
    {
      name: "action",
      align: "center",
      field: "action",
      sortable: false,
    },
  ],

  sitio: [
    {
      name: "descripcion",
      align: "left",
      label: "Descripción",
      field: "descripcion",
      sortable: true,
    },
    {
      name: "paisidentificador",
      align: "left",
      label: "Identificador País",
      field: "paisidentificador",
      sortable: true,
    },
    {
      name: "urlservidor",
      align: "left",
      label: "Url Servidor",
      field: "urlservidor",
      sortable: true,
    },
    {
      name: "activo",
      label: "Activo",
      field: "activo",
      sortable: true,
      align: "center",
    },
    {
      name: "action",
      align: "center",
      field: "action",
      sortable: false,
    },
  ],
  sucursal: [
    {
      name: "descripcion",
      align: "left",
      label: "Nombre",
      field: "descripcion",
      sortable: true,
    },
    {
      name: "abreviatura",
      align: "left",
      label: "Abreviatura",
      field: "abreviatura",
      sortable: true,
    },
    {
      name: "responsable",
      align: "left",
      label: "Responsable",
      field: "responsable",
      sortable: true,
    },
    {
      name: "direccion",
      align: "left",
      label: "Dirección",
      field: "direccion",
      sortable: true,
    },
    {
      name: "id_sitio",
      align: "left",
      label: "Sitio",
      field: "id_sitio",
      sortable: true,
    },
    {
      name: "activo",
      label: "Activo",
      field: "activo",
      sortable: true,
      align: "center",
    },
    {
      name: "action",
      align: "center",
      field: "action",
      sortable: false,
    },
  ],
  configuracion: [
    {
      name: "descripcion",
      align: "left",
      label: "Nombre",
      field: "descripcion",
      sortable: true,
    },
    {
      name: "id_sitio",
      align: "left",
      label: "Sitio",
      field: "id_sitio",
      sortable: true,
    },
    {
      name: "activo",
      label: "Activo",
      field: "activo",
      sortable: true,
      align: "center",
    },
    {
      name: "action",
      align: "center",
      field: "action",
      sortable: false,
    },
  ],
  tipositioubicacion: [
    {
      name: "descripcion",
      align: "left",
      label: "Descripción",
      field: "descripcion",
      sortable: true,
    },
    {
      name: "identificador",
      align: "left",
      label: "Identificador",
      field: "identificador",
      sortable: true,
    },
    {
      name: "activo",
      label: "Activo",
      field: "activo",
      sortable: true,
      align: "center",
    },
    {
      name: "action",
      align: "center",
      field: "action",
      sortable: false,
    },
  ],
  sitioubicacion: [
    {
      name: "descripcion",
      align: "left",
      label: "Nombre",
      field: "descripcion",
      sortable: true,
    },
    {
      name: "id_sitio",
      align: "left",
      label: "Sitio",
      field: "id_sitio",
      sortable: true,
    },
    {
      name: "id_tipositioubicacion",
      align: "left",
      label: "Id Tipo Sitio Ubicación",
      field: "id_tipositioubicacion",
      sortable: true,
    },
    {
      name: "id_ubicacionexterno",
      align: "left",
      label: "Id Ubicación Externo",
      field: "id_ubicacionexterno",
      sortable: true,
    },
    {
      name: "activo",
      label: "Activo",
      field: "activo",
      sortable: true,
      align: "center",
    },
    {
      name: "action",
      align: "center",
      field: "action",
      sortable: false,
    },
  ],
  generoconfiguracion: [
    {
      name: "id",
      required: true,
      label: "Id",
      align: "left",
      field: (row) => row.id,
      format: (val) => `${val}`,
      sortable: true,
    },
    {
      name: "descripcion",
      align: "left",
      label: "Descripción",
      field: "descripcion",
      sortable: true,
    },
    {
      name: "identificador",
      align: "left",
      label: "Identificador",
      field: "identificador",
      sortable: true,
    },
    {
      name: "paridad",
      align: "left",
      label: "Paridad",
      field: "paridad",
      sortable: true,
    },
    {
      name: "activo",
      label: "Activo",
      field: "activo",
      sortable: true,
      align: "center",
    },
    {
      name: "action",
      align: "center",
      field: "action",
      sortable: false,
    },
  ],
  // Agrega más configuraciones para otros modelos aquí...
};
